# 进程号
pid = "./run/client.pid"
# 开发模式。支持模式：debug、test、release（模式优先级：环境变量 < 配置文件 < 运行参数）
mode = "debug"
# 统一时区设置。项目中的时间获取请使用xtime.Now()
timezone = "Local"

# 集群客户端配置，常用于调试使用
[cluster.client]
    # 实例ID，网关集群中唯一。不填写默认自动生成唯一的实例ID
    id = ""
    # 实例名称
    name = "client"
    # 编解码器。可选：json | proto
    codec = "json"

[network.tcp.client]
    # 拨号地址
    addr = "gatesvr:3353"
    #addr = "localhost:3353"
    # 拨号超时时间，默认5s
    timeout = "5s"
    # 心跳间隔时间（秒），默认为10秒。设置为0则不启用心跳检测
    heartbeatInterval = "10s"
[crypto]
    # RSA设置
    [crypto.rsa]
        [crypto.rsa.encryptor]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：NORMAL | OAEP
            padding = "NORMAL"
            # 标签，加解密时必需一致
            label = ""
            # 加密数据块大小，单位字节。由于加密数据长度限制，需要对加密数据进行分块儿加密
            blockSize = 0
            # 公钥，可设置文件路径或公钥串
            publicKey = "./pem/key.pub.pem"
        [crypto.rsa.decryptor]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：NORMAL | OAEP
            padding = "NORMAL"
            # 标签。加解密时必需一致
            label = ""
            # 私钥。可设置文件路径或私钥串
            privateKey = "./pem/key.pem"
        [crypto.rsa.signer]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：PKCS | PSS
            padding = "PSS"
            # 私钥。可设置文件路径或私钥串
            privateKey = "./pem/key.pem"
        [crypto.rsa.verifier]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：PKCS | PSS
            padding = "PSS"
            # 公钥，可设置文件路径或公钥串
            publicKey = ""
[packet]
    # 字节序，默认为big。可选：little | big
    byteOrder = "big"
    # 路由字节数，默认为2字节
    routeBytes = 2
    # 序列号字节数，默认为2字节
    seqBytes = 2
    # 消息字节数，默认为5000字节
    bufferBytes = 100000

[log]
    # 日志输出文件
    file = "./log/due.log"
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "debug"
    # 日志输出格式，可选：text | json
    format = "text"
    # 是否输出到终端
    stdout = true
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxAge = "7d"
    # 文件最大尺寸限制，单位（MB）
    fileMaxSize = 100
    # 文件切割方式
    fileCutRule = "day"
    # 是否启用调用文件全路径
    callerFullPath = false
    # 是否启用分级存储
    classifiedStorage = false
