services:
  redis:
    image: redis:6.0
    container_name: dev-redis
    platform: linux/x86_64
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    command: ["redis-server", "--requirepass", "Zxy140522@"]
#    networks:
#      - middleware
  etcd:
    image: bitnami/etcd:latest
    container_name: dev-etcd
    platform: linux/x86_64
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://9.134.172.104:2379
    ports:
      - '2379:2379'
      - '2380:2380'
 